services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - 443:443/udp
      - "2019:2019"
    volumes:
      - ./data:/data/caddy
      - ./config:/config/caddy
      - ./certs:/certs
      - ./logs:/var/log/caddy
      - ../../web/public:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - homelab

networks:
  homelab:
    external: true
