services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:11.0.2
    container_name: forgejo
    restart: unless-stopped
    ports:
      - "2222:22"
      - "5050:3000" # for initial setup
    volumes:
      - ./data/forgejo:/data
    networks:
      waifunet:
        aliases:
          - forgy-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    networks:
      waifunet:
        aliases:
          - cloudflared-net

  glance:
    container_name: glance
    image: glanceapp/glance:latest
    restart: unless-stopped
    environment:
      - GLANCE_GITHUB_TOKEN=${GLANCE_GITHUB_TOKEN}
      - GLANCE_LOCATION=${GLANCE_LOCATION}
    volumes:
      - ./config/glance.yml:/app/config/glance.yml
    networks:
      waifunet:
        aliases:
          - glance-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./config/nginx:/etc/nginx:ro
      - ./web/public:/var/www:ro
    ports:
      - 9000:80
    networks:
      waifunet:
        aliases:
          - entrypoint

  swingmusic:
    container_name: swingmusic
    image: ghcr.io/swingmx/swingmusic:latest
    restart: unless-stopped
    volumes:
      - /home/dragsbruh/Music:/music:ro
      - ./data/swingmusic:/config
    ports:
      - 80:1970
    networks:
      waifunet:
        aliases:
          - music-net

networks:
  waifunet:
    name: waifunet
