services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:11.0.2
    container_name: forgejo
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - ./data/forgejo:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}

  glance:
    container_name: glance
    image: glanceapp/glance:latest
    restart: unless-stopped
    environment:
      - GLANCE_GITHUB_TOKEN=${GLANCE_GITHUB_TOKEN}
      - GLANCE_LOCATION=${GLANCE_LOCATION}
    volumes:
      - ./config/glance.yml:/app/config/glance.yml

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
      - 2019:2019
    volumes:
      - ./config:/etc/caddy
      - ./web/public:/srv
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./data/certs:/certs

  # swingmusic:
  #   container_name: swingmusic
  #   image: ghcr.io/swingmx/swingmusic:latest
  #   restart: unless-stopped
  #   volumes:
  #     - /home/dragsbruh/Music:/music:ro
  #     - ./data/swingmusic:/config

  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    volumes:
      - ./data/navidrome:/data
      - "/home/dragsbruh/Music:/music:ro"
    environment:
      - ND_LASTFM_APIKEY=${ND_LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${ND_LASTFM_SECRET}
      - ND_SPOTIFY_ID=${ND_SPOTIFY_ID}
      - ND_SPOTIFY_SECRET=${ND_SPOTIFY_SECRET}
    dns:
      - 1.1.1.1
      - 8.8.8.8

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /home/dragsbruh/.config/jellyfin:/config
      - /home/dragsbruh/.cache/jellyfin:/cache
      - /home/dragsbruh/Videos:/media:ro
      - /usr/share/fonts:/usr/local/share/fonts/custom:ro
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://fin.vinster.xyz
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
      - /dev/dri:/dev/dri

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /home/dragsbruh/Videos/Sacred:/srv
      - ./data/filebrowser/database:/database
      - ./data/filebrowser/config:/config

  httpeak:
    image: ghcr.io/dragsbruh/httpeak:latest
    container_name: httpeak

networks:
  waifunet:
    name: waifunet
