services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:11.0.2
    container_name: forgejo
    restart: unless-stopped
    ports:
      - "2222:22"
    volumes:
      - ./data/forgejo:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}

  glance:
    container_name: glance
    image: glanceapp/glance:latest
    restart: unless-stopped
    environment:
      - GLANCE_GITHUB_TOKEN=${GLANCE_GITHUB_TOKEN}
      - GLANCE_LOCATION=${GLANCE_LOCATION}
    volumes:
      - ./config/glance.yml:/app/config/glance.yml

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./config/nginx:/etc/nginx:ro
      - ./web/public:/var/www:ro
    ports:
      - 80:80

  swingmusic:
    container_name: swingmusic
    image: ghcr.io/swingmx/swingmusic:latest
    restart: unless-stopped
    volumes:
      - /home/dragsbruh/Music:/music:ro
      - ./data/swingmusic:/config

  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    volumes:
      - ./data/navidrome:/data
      - "/home/dragsbruh/Music:/music:ro"
    environment:
      - ND_LASTFM_APIKEY=${ND_LASTFM_APIKEY}
      - ND_LASTFM_SECRET=${ND_LASTFM_SECRET}
      - ND_SPOTIFY_ID=${ND_SPOTIFY_ID}
      - ND_SPOTIFY_SECRET=${ND_SPOTIFY_SECRET}

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "${UID}:${GID}"
    volumes:
      - /home/dragsbruh/.config/jellyfin:/config
      - /home/dragsbruh/.cache/jellyfin:/cache
      - /home/dragsbruh/Videos:/media:ro
      - /usr/share/fonts:/usr/local/share/fonts/custom:ro
    restart: unless-stopped
    environment:
      - JELLYFIN_PublishedServerUrl=https://fin.vinster.xyz
    extra_hosts:
      - "host.docker.internal:host-gateway"

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    volumes:
      - /home/dragsbruh/Videos/Sacred:/srv
      - ./data/filebrowser/database:/database
      - ./data/filebrowser/config:/config

networks:
  waifunet:
    name: waifunet
