services:
  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "2222:22"
      # - "5050:3000" # for initial setup
    volumes:
      - ./data/gitea:/data
    networks:
      waifunet:
        aliases:
          - waifutea-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    networks:
      waifunet:
        aliases:
          - cloudflared-net

  gitea_act_runner:
    image: gitea/act_runner:nightly
    container_name: gitea-act-runner
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/config.yml
      - GITEA_INSTANCE_URL=http://waifutea-net:3000/
      - GITEA_RUNNER_REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=waifumustact
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/gitea-act-runner.yml:/config.yml
      - ./data/gitea-act-runner:/data
      - ./scripts/act_init.sh:/init.sh
    depends_on:
      - gitea
    security_opt:
      - label=disable
    ports:
      - "7088:7088" # cache
    networks:
      waifunet:
        aliases:
          - waifutea-act-runner-net
    entrypoint: ["/sbin/tini", "--", "/init.sh"] # skips registration if registered

  glance:
    container_name: glance
    image: glanceapp/glance:latest
    restart: unless-stopped
    environment:
      - GLANCE_GITHUB_TOKEN=${GLANCE_GITHUB_TOKEN}
      - GLANCE_LOCATION=${GLANCE_LOCATION}
    volumes:
      - ./config/glance.yml:/app/config/glance.yml
    networks:
      waifunet:
        aliases:
          - glance-net

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
    command: --base-url=/portainer/
    networks:
      waifunet:
        aliases:
          - portainer-net

  proxii:
    image: proxii:latest
    container_name: proxii
    restart: unless-stopped
    volumes:
      - ./config/proxii.yml:/app/proxii.yml
      - ./web/public:/web/public
    networks:
      waifunet:
        aliases:
          - proxy-net

  uptime-kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:1
    volumes:
      - ./data/uptime-kuma:/app/data
    restart: unless-stopped
    networks:
      waifunet:
        aliases:
          - kuma-net

networks:
  waifunet:
    name: waifunet
