version: "3.8"

services:
  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: waifutea
    ports:
      - "2222:22"
      - "5050:3000" # for initial setup
    volumes:
      - ./data/waifutea:/data:Z
    networks:
      default:
        aliases:
          - waifutea-net

  act_runner:
    image: gitea/act_runner:nightly
    container_name: waifutea-act-runner
    environment:
      - CONFIG_FILE=/config.yml
      - GITEA_INSTANCE_URL=http://waifutea-net:3000/
      - GITEA_RUNNER_REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=waifumustact
    volumes:
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:Z
      - ./config/act-runner.yml:/config.yml:Z
      - ./data/act:/data:Z
      - ./scripts/act_init.sh:/init.sh:Z
    depends_on:
      - gitea
    security_opt:
      - label=disable
    ports:
      - "7088:7088" # cache
    networks:
      default:
        aliases:
          - waifutea-act-runner-net
    entrypoint: ["/sbin/tini", "--", "/init.sh"] # skips registration if registered

  proxii:
    image: waifuproxii:latest
    container_name: proxii
    ports:
      - "9000:3000"
    volumes:
      - ./config/proxii.yml:/app/proxii.yml
      - ./web/public:/web/public:Z
    networks:
      default:
        aliases:
          - proxii-net

  portainer:
    image: portainer-ce:latest
    container_name: portainer
    volumes:
      - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:Z
      - ./data/portainer:/data:Z
    command: --base-url=/portainer/
    networks:
      default:
        aliases:
          - portainer-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}

  #uptime-kuma:
  #  container_name: uptime_kuma
  #  image: louislam/uptime-kuma:1
  #  volumes:
  #    - ./data/uptime-kuma:/app/data
  #  restart: unless-stopped
  #  ports:
  #    - 3001:3001

networks:
  default:
    name: waifunet
