networks:
  public: null
  internal: null

include:
  - services/cloudflared.compose.yml
  - services/jellyfin.compose.yml
  - services/warpgate.compose.yml
  - services/httpeak.compose.yml
  - services/postgres/compose.yml
  - services/forgejo/compose.yml
  - services/glance/compose.yml
  - services/caddy/compose.yml
