version: "3.8"

networks:
  homelab:
    external: true

services:
  caddy:
    extends:
      file: ./apps/caddy/compose.yml
      service: caddy
    networks:
      - homelab

  cloudflared:
    extends:
      file: ./apps/cloudflared/compose.yml
      service: cloudflared
    networks:
      - homelab

  filebrowser:
    extends:
      file: ./apps/filebrowser/compose.yml
      service: filebrowser
    networks:
      - homelab

  forgejo:
    extends:
      file: ./apps/forgejo/compose.yml
      service: forgejo
    networks:
      - homelab

  glance:
    extends:
      file: ./apps/glance/compose.yml
      service: glance
    networks:
      - homelab

  httpeak:
    extends:
      file: ./apps/httpeak/compose.yml
      service: httpeak
    networks:
      - homelab

  jellyfin:
    extends:
      file: ./apps/jellyfin/compose.yml
      service: jellyfin
    networks:
      - homelab

  navidrome:
    extends:
      file: ./apps/navidrome/compose.yml
      service: navidrome
    networks:
      - homelab

  swing:
    extends:
      file: ./apps/swing/compose.yml
      service: swing
    networks:
      - homelab

