services:
  warpgate:
    image: ghcr.io/warp-tech/warpgate
    volumes:
      - ../heap/warpgate:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - internal
      - public
    restart: unless-stopped
