services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser
    volumes:
      - /home/dragsbruh/Documents:/srv/Documents
      - /home/dragsbruh/Videos:/srv/Videos
      - /home/dragsbruh/Pictures:/srv/Pictures
      - /home/dragsbruh/Music:/srv/Music
      - ./data:/database
      - ./settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - homelab

networks:
  homelab:
    external: true
