log:
  level: info

runner:
  file: /data/.runner
  capacity: 1
  env_file: /.env
  timeout: 3h
  shutdown_timeout: 0s
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 10s
  labels:
    - "alpine-latest:docker://alpine:latest"
    - "debian-slim:docker://debian:bookworm-slim"

cache:
  enabled: true
  dir: /data/cache
  host: ""
  port: 7088
  external_server: ""

container:
  network: ""
  privileged: false
  valid_volumes: []
  docker_host: ""
  force_pull: false
  force_rebuild: false

host:
  workdir_parent:
