port: 9000

services:
  - name: glance
    host: glance.vinster.xyz
    target:
      origin: http://glance-net:8080

  - name: gitea
    host: git.vinster.xyz
    target:
      origin: http://waifutea-net:3000

  - name: uptime kuma
    host: uptime.vinster.xyz
    target:
      origin: http://kuma-net:3001

  - name: portainer
    host: sudo.vinster.xyz
    target:
      origin: http://portainer-net:9000

  # - name: portainer locales (not required, but i dont like seeing them error messages)
  #   basePath: /locales
  #   host: sudo.vinster.xyz
  #   target:
  #     origin: http://portainer-net:9000
  #   trimBase: false

  - name: root
    host: vinster.xyz
    target:
      serveStatic: true
      staticDir: /web/public
