port: 9000

services:
  - name: glance
    host: glance.vinster.xyz
    target:
      origin: http://glance-net:8080
    enforceSecure: true

  - name: forgy
    host: git.vinster.xyz
    target:
      origin: http://forgy-net:3000
    enforceSecure: true

  - name: uptime kuma
    host: uptime.vinster.xyz
    target:
      origin: http://kuma-net:3001
    enforceSecure: true

  - name: portainer
    host: sudo.vinster.xyz
    target:
      origin: http://portainer-net:9000
    enforceSecure: true

  - name: root
    host: vinster.xyz
    target:
      serveStatic: true
      staticDir: /web/public
    enforceSecure: true
