services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - homelab
    command: tunnel run

networks:
  homelab:
    external: true
